---
- name: "Cleanup folder: {{ backup_dir_name }}"
  file:
    path: "{{ backup_dir }}"
    state: absent
  delegate_to: localhost
  run_once: true

- name: "Create folder: {{ backup_dir_name }}"
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: 0755
  delegate_to: localhost
  run_once: true

- include_tasks: "backup/{{ ansible_network_os }}.yml"
  when : 
    - not ansible_check_mode
    - ansible_network_os is defined
