---
- name: Set facts for DEPLOY
  ansible.builtin.set_fact:
    deploy_cfg: "{{ intended_config }}"

- name: Include tasks to deploy INTENDED config
  include_tasks: "deploy/{{ ansible_network_os }}.yml"
  when : 
  - ansible_network_os is defined
