---
- name: Save config to ftp server
  arista.eos.eos_command:
    commands: copyftp
    wait_for: result[0] contains 'Copy completed successfully.'

- name: Save config
  eos_config:
    save_when: always
  changed_when: false
