---
ansible_python_interpreter: "{{ ansible_playbook_python }}"
ansible_connection: ansible.netcommon.httpapi
ansible_network_os: arista.eos.eos

# Configure privilege escalation
ansible_become: true
ansible_become_method: enable

# HTTPAPI configuration
ansible_httpapi_port: 443
ansible_httpapi_host: '{{ ansible_host }}'
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false

management_interface: Management0
