---
tmp_dir: "{{ playbook_dir }}/../live"
tmp_hostdir: "{{ tmp_dir}}/{{ inventory_hostname }}"

# Input data
src_config: "{{ tmp_hostdir }}/config.cfg"

# Lookup REGEX
endpoint_regex: "(^interface\\s(?:Ethernet|Port-Channel)\\d+\\n(?:\\s{3}(?!description [cC]ore).*)+\\n!)\n"
core_links_regex: "(^interface.+\\n(?:\\s{3}description [cC]ore.+)\\n(?:\\s{3}.*\\n)+!)\\n"
# core_config: "(^(?:mlag configuration|router bfd|router ospf|interface Vxlan1|interface Loopback).*\\n(?:\\s{3}.+\\n)+!)\\n"
mgmt_config_regex: "(^(?:no )?(?:(?:ip route vrf mgmt|management|vrf instance mgmt|aaa root|username|hostname|clock timezone).*\\n(?:(?:\\s{3}.*\\n)?)*!|ip routing vrf mgmt))\n"

# Output data
split_config_dir: "{{ tmp_hostdir }}/new_config"
new_config: "{{ tmp_hostdir }}/new_config.cfg"

# Split config:
working_config: "{{ split_config_dir }}/working.cfg"
endpoint_cfg: "{{ split_config_dir }}/endpoints.cfg"
mgmt_cfg: "{{ split_config_dir }}/management.cfg"
