---

- name: Gather configuration
  arista.eos.eos_facts:
    gather_subset:
    - 'config'
  register: eos_facts

- name: "Save configuration"
  copy: 
    content: "{{ eos_facts.ansible_facts.ansible_net_config }}"
    dest: "{{ src_config }}"
