---

- name: Gather all facts except hardware
  arista.eos.eos_facts:
    gather_subset:
    - '!hardware'
  when: ansible_network_os == 'arista.eos.eos'
  register: eos_facts

- name: "Save IP addresses"
  copy: 
    content: "{{ eos_facts.ansible_facts.ansible_net_all_ipv4_addresses | join('\n')}}"
    dest: "{{ tmp_hostdir }}/ip_addresses.txt"

- name: "Save config"
  copy: 
    content: "{{ eos_facts.ansible_facts.ansible_net_config }}"
    dest: "{{ tmp_hostdir }}/config.txt"

- name: "Save interface data"
  copy: 
    content: "{{ eos_facts.ansible_facts.ansible_net_interfaces | to_nice_yaml }}"
    dest: "{{ tmp_hostdir }}/interface.yml"

- name: "Save neighbor data"
  copy: 
    content: "{{ eos_facts.ansible_facts.ansible_net_neighbors | to_nice_yaml }}"
    dest: "{{ tmp_hostdir }}/neighbor.yml"
