---

- name: Ensure output dirs exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ backup_dir }}"
  run_once: true
  changed_when: false

- import_tasks: eos.yml
  when: ansible_network_os == 'arista.eos.eos'
